global:
  scrape_interval: 5s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s  # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/alertmanager/alerting.rules.yml"
#  - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.1.166:9100"]
        labels:
          app: "node_exporter"

  - job_name: "c-advisor"
    static_configs:
      - targets: ["localhost:8082"]
        labels:
          app: "c-advisor"

  - job_name: "url_shortener"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.1.166:7000"]
        labels:
          app: "shorten_web_app"
